/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateVideo200,
  CreateVideoBodyOne,
  CreateVideoBodyThree,
  CreateVideoBodyTwo,
  EditVideo200,
  EditVideoBodyOne,
  EditVideoBodyThree,
  EditVideoBodyTwo,
  ListVideos200,
  ListVideosParams,
  MyVideos200,
  MyVideosParams,
  RecordView200,
  RemoveVideo200,
  ShowVideo200,
  ShowVideoAuthed200
} from '../model';





/**
 * list all public videos
 * @summary list
 */
export type listVideosResponse200 = {
  data: ListVideos200
  status: 200
}

export type listVideosResponseSuccess = (listVideosResponse200) & {
  headers: Headers;
};
;

export type listVideosResponse = (listVideosResponseSuccess)

export const getListVideosUrl = (params: ListVideosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/videos/?${stringifiedParams}` : `http://localhost:3000/api/videos/`
}

export const listVideos = async (params: ListVideosParams, options?: RequestInit): Promise<listVideosResponse> => {

  const res = await fetch(getListVideosUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listVideosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listVideosResponse
}





export const getListVideosQueryKey = (params?: ListVideosParams,) => {
    return [
    `http://localhost:3000/api/videos/`, ...(params ? [params] : [])
    ] as const;
    }


export const getListVideosQueryOptions = <TData = Awaited<ReturnType<typeof listVideos>>, TError = unknown>(params: ListVideosParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVideosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({ signal }) => listVideos(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVideosQueryResult = NonNullable<Awaited<ReturnType<typeof listVideos>>>
export type ListVideosQueryError = unknown


/**
 * @summary list
 */

export function createListVideos<TData = Awaited<ReturnType<typeof listVideos>>, TError = unknown>(
 params: () =>  ListVideosParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListVideosQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * get a video by id
 * @summary show
 */
export type showVideoResponse200 = {
  data: ShowVideo200
  status: 200
}

export type showVideoResponseSuccess = (showVideoResponse200) & {
  headers: Headers;
};
;

export type showVideoResponse = (showVideoResponseSuccess)

export const getShowVideoUrl = (id: string,) => {




  return `http://localhost:3000/api/videos/show/${id}`
}

export const showVideo = async (id: string, options?: RequestInit): Promise<showVideoResponse> => {

  const res = await fetch(getShowVideoUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showVideoResponse
}





export const getShowVideoQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/api/videos/show/${id}`
    ] as const;
    }


export const getShowVideoQueryOptions = <TData = Awaited<ReturnType<typeof showVideo>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showVideo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowVideoQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showVideo>>> = ({ signal }) => showVideo(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showVideo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowVideoQueryResult = NonNullable<Awaited<ReturnType<typeof showVideo>>>
export type ShowVideoQueryError = unknown


/**
 * @summary show
 */

export function createShowVideo<TData = Awaited<ReturnType<typeof showVideo>>, TError = unknown>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showVideo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getShowVideoQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * get a video by id with reaction and subscription status
 * @summary showAuthed
 */
export type showVideoAuthedResponse200 = {
  data: ShowVideoAuthed200
  status: 200
}

export type showVideoAuthedResponseSuccess = (showVideoAuthedResponse200) & {
  headers: Headers;
};
;

export type showVideoAuthedResponse = (showVideoAuthedResponseSuccess)

export const getShowVideoAuthedUrl = (id: string,) => {




  return `http://localhost:3000/api/videos/show/${id}/authed`
}

export const showVideoAuthed = async (id: string, options?: RequestInit): Promise<showVideoAuthedResponse> => {

  const res = await fetch(getShowVideoAuthedUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showVideoAuthedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showVideoAuthedResponse
}





export const getShowVideoAuthedQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/api/videos/show/${id}/authed`
    ] as const;
    }


export const getShowVideoAuthedQueryOptions = <TData = Awaited<ReturnType<typeof showVideoAuthed>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showVideoAuthed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowVideoAuthedQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showVideoAuthed>>> = ({ signal }) => showVideoAuthed(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showVideoAuthed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowVideoAuthedQueryResult = NonNullable<Awaited<ReturnType<typeof showVideoAuthed>>>
export type ShowVideoAuthedQueryError = unknown


/**
 * @summary showAuthed
 */

export function createShowVideoAuthed<TData = Awaited<ReturnType<typeof showVideoAuthed>>, TError = unknown>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showVideoAuthed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getShowVideoAuthedQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * list the authenticated user's channel videos
 * @summary myList
 */
export type myVideosResponse200 = {
  data: MyVideos200
  status: 200
}

export type myVideosResponseSuccess = (myVideosResponse200) & {
  headers: Headers;
};
;

export type myVideosResponse = (myVideosResponseSuccess)

export const getMyVideosUrl = (params: MyVideosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/videos/me?${stringifiedParams}` : `http://localhost:3000/api/videos/me`
}

export const myVideos = async (params: MyVideosParams, options?: RequestInit): Promise<myVideosResponse> => {

  const res = await fetch(getMyVideosUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: myVideosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as myVideosResponse
}





export const getMyVideosQueryKey = (params?: MyVideosParams,) => {
    return [
    `http://localhost:3000/api/videos/me`, ...(params ? [params] : [])
    ] as const;
    }


export const getMyVideosQueryOptions = <TData = Awaited<ReturnType<typeof myVideos>>, TError = unknown>(params: MyVideosParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myVideos>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMyVideosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof myVideos>>> = ({ signal }) => myVideos(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof myVideos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MyVideosQueryResult = NonNullable<Awaited<ReturnType<typeof myVideos>>>
export type MyVideosQueryError = unknown


/**
 * @summary myList
 */

export function createMyVideos<TData = Awaited<ReturnType<typeof myVideos>>, TError = unknown>(
 params: () =>  MyVideosParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myVideos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getMyVideosQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * upload a video to the authenticated user's channel
 * @summary create
 */
export type createVideoResponse200 = {
  data: CreateVideo200
  status: 200
}

export type createVideoResponseSuccess = (createVideoResponse200) & {
  headers: Headers;
};
;

export type createVideoResponse = (createVideoResponseSuccess)

export const getCreateVideoUrl = () => {




  return `http://localhost:3000/api/videos/me`
}

export const createVideo = async (createVideoBody: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree, options?: RequestInit): Promise<createVideoResponse> => {

  const res = await fetch(getCreateVideoUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      createVideoBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createVideoResponse
}




export const getCreateVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createVideo>>, TError,{data: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createVideo>>, TError,{data: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree}, TContext> => {

const mutationKey = ['createVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVideo>>, {data: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  createVideo(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateVideoMutationResult = NonNullable<Awaited<ReturnType<typeof createVideo>>>
    export type CreateVideoMutationBody = CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree
    export type CreateVideoMutationError = unknown

    /**
 * @summary create
 */
export const createCreateVideo = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createVideo>>, TError,{data: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createVideo>>,
        TError,
        {data: CreateVideoBodyOne | CreateVideoBodyTwo | CreateVideoBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateVideoMutationOptions(options?.()) }), queryClient);
    }
    /**
 * update a video owned by the authenticated user
 * @summary edit
 */
export type editVideoResponse200 = {
  data: EditVideo200
  status: 200
}

export type editVideoResponseSuccess = (editVideoResponse200) & {
  headers: Headers;
};
;

export type editVideoResponse = (editVideoResponseSuccess)

export const getEditVideoUrl = (id: string,) => {




  return `http://localhost:3000/api/videos/me/${id}`
}

export const editVideo = async (id: string,
    editVideoBody: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree, options?: RequestInit): Promise<editVideoResponse> => {

  const res = await fetch(getEditVideoUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(
      editVideoBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editVideoResponse
}




export const getEditVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editVideo>>, TError,{id: string;data: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof editVideo>>, TError,{id: string;data: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree}, TContext> => {

const mutationKey = ['editVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editVideo>>, {id: string;data: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  editVideo(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditVideoMutationResult = NonNullable<Awaited<ReturnType<typeof editVideo>>>
    export type EditVideoMutationBody = EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree
    export type EditVideoMutationError = unknown

    /**
 * @summary edit
 */
export const createEditVideo = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editVideo>>, TError,{id: string;data: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof editVideo>>,
        TError,
        {id: string;data: EditVideoBodyOne | EditVideoBodyTwo | EditVideoBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getEditVideoMutationOptions(options?.()) }), queryClient);
    }
    /**
 * delete a video owned by the authenticated user
 * @summary remove
 */
export type removeVideoResponse200 = {
  data: RemoveVideo200
  status: 200
}

export type removeVideoResponseSuccess = (removeVideoResponse200) & {
  headers: Headers;
};
;

export type removeVideoResponse = (removeVideoResponseSuccess)

export const getRemoveVideoUrl = (id: string,) => {




  return `http://localhost:3000/api/videos/me/${id}`
}

export const removeVideo = async (id: string, options?: RequestInit): Promise<removeVideoResponse> => {

  const res = await fetch(getRemoveVideoUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeVideoResponse
}




export const getRemoveVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeVideo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof removeVideo>>, TError,{id: string}, TContext> => {

const mutationKey = ['removeVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeVideo>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  removeVideo(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveVideoMutationResult = NonNullable<Awaited<ReturnType<typeof removeVideo>>>

    export type RemoveVideoMutationError = unknown

    /**
 * @summary remove
 */
export const createRemoveVideo = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeVideo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removeVideo>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRemoveVideoMutationOptions(options?.()) }), queryClient);
    }
    /**
 * record a view for a video by the authenticated user
 * @summary recordView
 */
export type recordViewResponse200 = {
  data: RecordView200
  status: 200
}

export type recordViewResponseSuccess = (recordViewResponse200) & {
  headers: Headers;
};
;

export type recordViewResponse = (recordViewResponseSuccess)

export const getRecordViewUrl = (id: string,) => {




  return `http://localhost:3000/api/videos/show/${id}/view`
}

export const recordView = async (id: string, options?: RequestInit): Promise<recordViewResponse> => {

  const res = await fetch(getRecordViewUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recordViewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as recordViewResponse
}




export const getRecordViewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof recordView>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof recordView>>, TError,{id: string}, TContext> => {

const mutationKey = ['recordView'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recordView>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  recordView(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RecordViewMutationResult = NonNullable<Awaited<ReturnType<typeof recordView>>>

    export type RecordViewMutationError = unknown

    /**
 * @summary recordView
 */
export const createRecordView = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof recordView>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof recordView>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRecordViewMutationOptions(options?.()) }), queryClient);
    }
