/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CommentReact200,
  CommentReactBodyOne,
  CommentReactBodyThree,
  CommentReactBodyTwo,
  CreateComment200,
  CreateCommentBodyOne,
  CreateCommentBodyThree,
  CreateCommentBodyTwo,
  EditComment200,
  EditCommentBodyOne,
  EditCommentBodyThree,
  EditCommentBodyTwo,
  ListComments200,
  ListCommentsAuthed200,
  ListCommentsAuthedParams,
  ListCommentsParams,
  RemoveComment200
} from '../model';





/**
 * list comments for a video
 * @summary list
 */
export type listCommentsResponse200 = {
  data: ListComments200
  status: 200
}

export type listCommentsResponseSuccess = (listCommentsResponse200) & {
  headers: Headers;
};
;

export type listCommentsResponse = (listCommentsResponseSuccess)

export const getListCommentsUrl = (videoId: string,
    params: ListCommentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/comments/${videoId}?${stringifiedParams}` : `http://localhost:3000/api/comments/${videoId}`
}

export const listComments = async (videoId: string,
    params: ListCommentsParams, options?: RequestInit): Promise<listCommentsResponse> => {

  const res = await fetch(getListCommentsUrl(videoId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listCommentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listCommentsResponse
}





export const getListCommentsQueryKey = (videoId: string,
    params?: ListCommentsParams,) => {
    return [
    `http://localhost:3000/api/comments/${videoId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(videoId: string,
    params: ListCommentsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(videoId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(videoId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = unknown


/**
 * @summary list
 */

export function createListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 videoId: () =>  string,
    params: () =>  ListCommentsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListCommentsQueryOptions(videoId(),
    params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * post a comment on a video
 * @summary create
 */
export type createCommentResponse200 = {
  data: CreateComment200
  status: 200
}

export type createCommentResponseSuccess = (createCommentResponse200) & {
  headers: Headers;
};
;

export type createCommentResponse = (createCommentResponseSuccess)

export const getCreateCommentUrl = (videoId: string,) => {




  return `http://localhost:3000/api/comments/${videoId}`
}

export const createComment = async (videoId: string,
    createCommentBody: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree, options?: RequestInit): Promise<createCommentResponse> => {

  const res = await fetch(getCreateCommentUrl(videoId),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      createCommentBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createCommentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCommentResponse
}




export const getCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{videoId: string;data: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{videoId: string;data: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree}, TContext> => {

const mutationKey = ['createComment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComment>>, {videoId: string;data: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree}> = (props) => {
          const {videoId,data} = props ?? {};

          return  createComment(videoId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
    export type CreateCommentMutationBody = CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree
    export type CreateCommentMutationError = unknown

    /**
 * @summary create
 */
export const createCreateComment = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{videoId: string;data: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createComment>>,
        TError,
        {videoId: string;data: CreateCommentBodyOne | CreateCommentBodyTwo | CreateCommentBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateCommentMutationOptions(options?.()) }), queryClient);
    }
    /**
 * list comments for a video with my reaction
 * @summary listAuthed
 */
export type listCommentsAuthedResponse200 = {
  data: ListCommentsAuthed200
  status: 200
}

export type listCommentsAuthedResponseSuccess = (listCommentsAuthedResponse200) & {
  headers: Headers;
};
;

export type listCommentsAuthedResponse = (listCommentsAuthedResponseSuccess)

export const getListCommentsAuthedUrl = (videoId: string,
    params: ListCommentsAuthedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/comments/${videoId}/authed?${stringifiedParams}` : `http://localhost:3000/api/comments/${videoId}/authed`
}

export const listCommentsAuthed = async (videoId: string,
    params: ListCommentsAuthedParams, options?: RequestInit): Promise<listCommentsAuthedResponse> => {

  const res = await fetch(getListCommentsAuthedUrl(videoId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listCommentsAuthedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listCommentsAuthedResponse
}





export const getListCommentsAuthedQueryKey = (videoId: string,
    params?: ListCommentsAuthedParams,) => {
    return [
    `http://localhost:3000/api/comments/${videoId}/authed`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCommentsAuthedQueryOptions = <TData = Awaited<ReturnType<typeof listCommentsAuthed>>, TError = unknown>(videoId: string,
    params: ListCommentsAuthedParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listCommentsAuthed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsAuthedQueryKey(videoId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCommentsAuthed>>> = ({ signal }) => listCommentsAuthed(videoId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listCommentsAuthed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsAuthedQueryResult = NonNullable<Awaited<ReturnType<typeof listCommentsAuthed>>>
export type ListCommentsAuthedQueryError = unknown


/**
 * @summary listAuthed
 */

export function createListCommentsAuthed<TData = Awaited<ReturnType<typeof listCommentsAuthed>>, TError = unknown>(
 videoId: () =>  string,
    params: () =>  ListCommentsAuthedParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listCommentsAuthed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListCommentsAuthedQueryOptions(videoId(),
    params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * edit an owned comment
 * @summary edit
 */
export type editCommentResponse200 = {
  data: EditComment200
  status: 200
}

export type editCommentResponseSuccess = (editCommentResponse200) & {
  headers: Headers;
};
;

export type editCommentResponse = (editCommentResponseSuccess)

export const getEditCommentUrl = (id: string,) => {




  return `http://localhost:3000/api/comments/me/${id}`
}

export const editComment = async (id: string,
    editCommentBody: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree, options?: RequestInit): Promise<editCommentResponse> => {

  const res = await fetch(getEditCommentUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(
      editCommentBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editCommentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editCommentResponse
}




export const getEditCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editComment>>, TError,{id: string;data: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof editComment>>, TError,{id: string;data: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree}, TContext> => {

const mutationKey = ['editComment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editComment>>, {id: string;data: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  editComment(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditCommentMutationResult = NonNullable<Awaited<ReturnType<typeof editComment>>>
    export type EditCommentMutationBody = EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree
    export type EditCommentMutationError = unknown

    /**
 * @summary edit
 */
export const createEditComment = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editComment>>, TError,{id: string;data: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof editComment>>,
        TError,
        {id: string;data: EditCommentBodyOne | EditCommentBodyTwo | EditCommentBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getEditCommentMutationOptions(options?.()) }), queryClient);
    }
    /**
 * delete an owned comment
 * @summary remove
 */
export type removeCommentResponse200 = {
  data: RemoveComment200
  status: 200
}

export type removeCommentResponseSuccess = (removeCommentResponse200) & {
  headers: Headers;
};
;

export type removeCommentResponse = (removeCommentResponseSuccess)

export const getRemoveCommentUrl = (id: string,) => {




  return `http://localhost:3000/api/comments/me/${id}`
}

export const removeComment = async (id: string, options?: RequestInit): Promise<removeCommentResponse> => {

  const res = await fetch(getRemoveCommentUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeCommentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeCommentResponse
}




export const getRemoveCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeComment>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof removeComment>>, TError,{id: string}, TContext> => {

const mutationKey = ['removeComment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeComment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  removeComment(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveCommentMutationResult = NonNullable<Awaited<ReturnType<typeof removeComment>>>

    export type RemoveCommentMutationError = unknown

    /**
 * @summary remove
 */
export const createRemoveComment = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeComment>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removeComment>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRemoveCommentMutationOptions(options?.()) }), queryClient);
    }
    /**
 * like or dislike a comment — toggles off if same type sent again
 * @summary react
 */
export type commentReactResponse200 = {
  data: CommentReact200
  status: 200
}

export type commentReactResponseSuccess = (commentReactResponse200) & {
  headers: Headers;
};
;

export type commentReactResponse = (commentReactResponseSuccess)

export const getCommentReactUrl = (id: string,) => {




  return `http://localhost:3000/api/comments/react/${id}`
}

export const commentReact = async (id: string,
    commentReactBody: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree, options?: RequestInit): Promise<commentReactResponse> => {

  const res = await fetch(getCommentReactUrl(id),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      commentReactBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commentReactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentReactResponse
}




export const getCommentReactMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof commentReact>>, TError,{id: string;data: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof commentReact>>, TError,{id: string;data: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree}, TContext> => {

const mutationKey = ['commentReact'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commentReact>>, {id: string;data: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  commentReact(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommentReactMutationResult = NonNullable<Awaited<ReturnType<typeof commentReact>>>
    export type CommentReactMutationBody = CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree
    export type CommentReactMutationError = unknown

    /**
 * @summary react
 */
export const createCommentReact = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof commentReact>>, TError,{id: string;data: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof commentReact>>,
        TError,
        {id: string;data: CommentReactBodyOne | CommentReactBodyTwo | CommentReactBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getCommentReactMutationOptions(options?.()) }), queryClient);
    }
