volumes:
  pg_data:

services:
  db:
    image: postgres:16-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omar"]
      interval: 5s
      timeout: 3s
      retries: 5
