/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AddVideoToPlaylist200Data } from './addVideoToPlaylist200Data';

export type AddVideoToPlaylist200 = {
  success: boolean;
  data: AddVideoToPlaylist200Data;
  message?: string;
};
