/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CommentReactBodyOneType = typeof CommentReactBodyOneType[keyof typeof CommentReactBodyOneType];


export const CommentReactBodyOneType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
