/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CommentReactBodyOneType } from './commentReactBodyOneType';

export type CommentReactBodyOne = {
  type: CommentReactBodyOneType;
};
