/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CommentReact200Data } from './commentReact200Data';

export type CommentReact200 = {
  success: boolean;
  data: CommentReact200Data;
  message?: string;
};
