/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateVideo200Data } from './createVideo200Data';

export type CreateVideo200 = {
  success: boolean;
  data: CreateVideo200Data;
  message?: string;
};
