/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateVideoBodyOneVisibility } from './createVideoBodyOneVisibility';

export type CreateVideoBodyOne = {
  title: string;
  description?: string | null;
  visibility?: CreateVideoBodyOneVisibility;
  video: Blob;
  thumbnail?: Blob;
};
