/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreatePlaylist200Data } from './createPlaylist200Data';

export type CreatePlaylist200 = {
  success: boolean;
  data: CreatePlaylist200Data;
  message?: string;
};
