/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateVideoBodyThreeVisibility } from './createVideoBodyThreeVisibility';

export type CreateVideoBodyThree = {
  title: string;
  description?: string | null;
  visibility?: CreateVideoBodyThreeVisibility;
  video: Blob;
  thumbnail?: Blob;
};
