/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreateVideoBodyOneVisibility = typeof CreateVideoBodyOneVisibility[keyof typeof CreateVideoBodyOneVisibility];


export const CreateVideoBodyOneVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
