/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateChannel200Data } from './createChannel200Data';

export type CreateChannel200 = {
  success: boolean;
  data: CreateChannel200Data;
  message?: string;
};
