/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreateVideo200DataVisibility = typeof CreateVideo200DataVisibility[keyof typeof CreateVideo200DataVisibility];


export const CreateVideo200DataVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
