/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreatePlaylist200DataVisibility } from './createPlaylist200DataVisibility';

export type CreatePlaylist200Data = {
  id: string;
  name: string;
  description: string | null;
  visibility: CreatePlaylist200DataVisibility;
  userId: string;
  videoCount: number;
  createdAt: string;
  updatedAt: string;
};
