/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreatePlaylistBodyTwoVisibility = typeof CreatePlaylistBodyTwoVisibility[keyof typeof CreatePlaylistBodyTwoVisibility];


export const CreatePlaylistBodyTwoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
