/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreatePlaylistBodyTwoVisibility } from './createPlaylistBodyTwoVisibility';

export type CreatePlaylistBodyTwo = {
  /** @minLength 1 */
  name: string;
  description?: string | null;
  visibility?: CreatePlaylistBodyTwoVisibility;
};
