/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateVideoBodyTwoVisibility } from './createVideoBodyTwoVisibility';

export type CreateVideoBodyTwo = {
  title: string;
  description?: string | null;
  visibility?: CreateVideoBodyTwoVisibility;
  video: Blob;
  thumbnail?: Blob;
};
