/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { CreateComment200Data } from './createComment200Data';

export type CreateComment200 = {
  success: boolean;
  data: CreateComment200Data;
  message?: string;
};
