/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreateVideoBodyThreeVisibility = typeof CreateVideoBodyThreeVisibility[keyof typeof CreateVideoBodyThreeVisibility];


export const CreateVideoBodyThreeVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
