/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreatePlaylist200DataVisibility = typeof CreatePlaylist200DataVisibility[keyof typeof CreatePlaylist200DataVisibility];


export const CreatePlaylist200DataVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
