/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditPlaylist200DataVisibility } from './editPlaylist200DataVisibility';

export type EditPlaylist200Data = {
  id: string;
  name: string;
  description: string | null;
  visibility: EditPlaylist200DataVisibility;
  userId: string;
  videoCount: number;
  createdAt: string;
  updatedAt: string;
};
