/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type EditChannelBodyOne = {
  name?: string;
  description?: string | null;
  avatar?: Blob;
  banner?: Blob;
};
