/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditVideo200DataVisibility } from './editVideo200DataVisibility';

export type EditVideo200Data = {
  id: string;
  channelId: string;
  channelName: string;
  title: string;
  description: string | null;
  videoUrl: string;
  thumbnailUrl: string | null;
  visibility: EditVideo200DataVisibility;
  views: number;
  createdAt: string;
  updatedAt: string;
};
