/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditVideoBodyOneVisibility } from './editVideoBodyOneVisibility';

export type EditVideoBodyOne = {
  title?: string;
  description?: string | null;
  visibility?: EditVideoBodyOneVisibility;
  thumbnail?: Blob;
};
