/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditPlaylist200Data } from './editPlaylist200Data';

export type EditPlaylist200 = {
  success: boolean;
  data: EditPlaylist200Data;
  message?: string;
};
