/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditComment200DataUser } from './editComment200DataUser';

export type EditComment200Data = {
  id: string;
  content: string;
  videoId: string;
  userId: string;
  parentId: string | null;
  replyCount: number;
  likes: number;
  dislikes: number;
  myReaction: 'LIKE' | 'DISLIKE' | null;
  user: EditComment200DataUser;
  createdAt: string;
  updatedAt: string;
};
