/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type EditPlaylistBodyTwoVisibility = typeof EditPlaylistBodyTwoVisibility[keyof typeof EditPlaylistBodyTwoVisibility];


export const EditPlaylistBodyTwoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
