/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type EditVideoBodyThreeVisibility = typeof EditVideoBodyThreeVisibility[keyof typeof EditVideoBodyThreeVisibility];


export const EditVideoBodyThreeVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
