/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditComment200Data } from './editComment200Data';

export type EditComment200 = {
  success: boolean;
  data: EditComment200Data;
  message?: string;
};
