/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type EditVideoBodyOneVisibility = typeof EditVideoBodyOneVisibility[keyof typeof EditVideoBodyOneVisibility];


export const EditVideoBodyOneVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
