/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditVideoBodyTwoVisibility } from './editVideoBodyTwoVisibility';

export type EditVideoBodyTwo = {
  title?: string;
  description?: string | null;
  visibility?: EditVideoBodyTwoVisibility;
  thumbnail?: Blob;
};
