/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditVideo200Data } from './editVideo200Data';

export type EditVideo200 = {
  success: boolean;
  data: EditVideo200Data;
  message?: string;
};
