/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type EditPlaylistBodyOneVisibility = typeof EditPlaylistBodyOneVisibility[keyof typeof EditPlaylistBodyOneVisibility];


export const EditPlaylistBodyOneVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
