/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { EditChannel200Data } from './editChannel200Data';

export type EditChannel200 = {
  success: boolean;
  data: EditChannel200Data;
  message?: string;
};
