/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ListVideos200DataItemVisibility = typeof ListVideos200DataItemVisibility[keyof typeof ListVideos200DataItemVisibility];


export const ListVideos200DataItemVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
