/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListCommentsAuthed200DataItem } from './listCommentsAuthed200DataItem';
import type { ListCommentsAuthed200Meta } from './listCommentsAuthed200Meta';

export type ListCommentsAuthed200 = {
  success: boolean;
  data: ListCommentsAuthed200DataItem[];
  meta?: ListCommentsAuthed200Meta;
  message?: string;
};
