/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListVideos200DataItem } from './listVideos200DataItem';
import type { ListVideos200Meta } from './listVideos200Meta';

export type ListVideos200 = {
  success: boolean;
  data: ListVideos200DataItem[];
  meta?: ListVideos200Meta;
  message?: string;
};
