/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListCommentsAuthed200DataItemUser } from './listCommentsAuthed200DataItemUser';

export type ListCommentsAuthed200DataItem = {
  id: string;
  content: string;
  videoId: string;
  userId: string;
  parentId: string | null;
  replyCount: number;
  likes: number;
  dislikes: number;
  myReaction: 'LIKE' | 'DISLIKE' | null;
  user: ListCommentsAuthed200DataItemUser;
  createdAt: string;
  updatedAt: string;
};
