/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListComments200DataItem } from './listComments200DataItem';
import type { ListComments200Meta } from './listComments200Meta';

export type ListComments200 = {
  success: boolean;
  data: ListComments200DataItem[];
  meta?: ListComments200Meta;
  message?: string;
};
