/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListChannels200DataItem } from './listChannels200DataItem';
import type { ListChannels200Meta } from './listChannels200Meta';

export type ListChannels200 = {
  success: boolean;
  data: ListChannels200DataItem[];
  meta?: ListChannels200Meta;
  message?: string;
};
