/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListMyPlaylists200DataItemVisibility } from './listMyPlaylists200DataItemVisibility';

export type ListMyPlaylists200DataItem = {
  id: string;
  name: string;
  description: string | null;
  visibility: ListMyPlaylists200DataItemVisibility;
  userId: string;
  videoCount: number;
  createdAt: string;
  updatedAt: string;
};
