/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ListMyPlaylists200DataItemVisibility = typeof ListMyPlaylists200DataItemVisibility[keyof typeof ListMyPlaylists200DataItemVisibility];


export const ListMyPlaylists200DataItemVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
