/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListVideos200DataItemVisibility } from './listVideos200DataItemVisibility';

export type ListVideos200DataItem = {
  id: string;
  channelId: string;
  channelName: string;
  title: string;
  description: string | null;
  videoUrl: string;
  thumbnailUrl: string | null;
  visibility: ListVideos200DataItemVisibility;
  views: number;
  createdAt: string;
  updatedAt: string;
};
