/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ListVideos200Meta = {
  page: number;
  size: number;
  total: number;
  totalPages: number;
};
