/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListMyPlaylists200DataItem } from './listMyPlaylists200DataItem';
import type { ListMyPlaylists200Meta } from './listMyPlaylists200Meta';

export type ListMyPlaylists200 = {
  success: boolean;
  data: ListMyPlaylists200DataItem[];
  meta?: ListMyPlaylists200Meta;
  message?: string;
};
