/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyChannel200Data } from './myChannel200Data';

export type MyChannel200 = {
  success: boolean;
  data: MyChannel200Data;
  message?: string;
};
