/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type MyChannel200Data = {
  id: string;
  name: string;
  description: string | null;
  avatarUrl: string | null;
  bannerUrl: string | null;
  userId: string;
  subscriberCount: number;
  isSubscribed: boolean;
  createdAt: string;
  updatedAt: string;
};
