/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type MyFeed200DataItemVisibility = typeof MyFeed200DataItemVisibility[keyof typeof MyFeed200DataItemVisibility];


export const MyFeed200DataItemVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
