/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyFeed200DataItem } from './myFeed200DataItem';
import type { MyFeed200Meta } from './myFeed200Meta';

export type MyFeed200 = {
  success: boolean;
  data: MyFeed200DataItem[];
  meta?: MyFeed200Meta;
  message?: string;
};
