/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyFeed200DataItemChannel } from './myFeed200DataItemChannel';
import type { MyFeed200DataItemVisibility } from './myFeed200DataItemVisibility';

export type MyFeed200DataItem = {
  id: string;
  title: string;
  description: string | null;
  thumbnailUrl: string | null;
  videoUrl: string;
  visibility: MyFeed200DataItemVisibility;
  views: number;
  channelId: string;
  channel: MyFeed200DataItemChannel;
  createdAt: string;
  updatedAt: string;
};
