/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type MyReactions200DataItemType = typeof MyReactions200DataItemType[keyof typeof MyReactions200DataItemType];


export const MyReactions200DataItemType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
