/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyReactions200DataItem } from './myReactions200DataItem';
import type { MyReactions200Meta } from './myReactions200Meta';

export type MyReactions200 = {
  success: boolean;
  data: MyReactions200DataItem[];
  meta?: MyReactions200Meta;
  message?: string;
};
