/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyReactions200DataItemType } from './myReactions200DataItemType';
import type { MyReactions200DataItemVideo } from './myReactions200DataItemVideo';

export type MyReactions200DataItem = {
  id: string;
  type: MyReactions200DataItemType;
  video: MyReactions200DataItemVideo;
  createdAt: string;
};
