/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type MyReactionsType = typeof MyReactionsType[keyof typeof MyReactionsType];


export const MyReactionsType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
