/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MySubscriptions200DataItem } from './mySubscriptions200DataItem';
import type { MySubscriptions200Meta } from './mySubscriptions200Meta';

export type MySubscriptions200 = {
  success: boolean;
  data: MySubscriptions200DataItem[];
  meta?: MySubscriptions200Meta;
  message?: string;
};
