/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyVideos200DataItemVisibility } from './myVideos200DataItemVisibility';

export type MyVideos200DataItem = {
  id: string;
  channelId: string;
  channelName: string;
  title: string;
  description: string | null;
  videoUrl: string;
  thumbnailUrl: string | null;
  visibility: MyVideos200DataItemVisibility;
  views: number;
  createdAt: string;
  updatedAt: string;
};
