/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type MyVideos200DataItemVisibility = typeof MyVideos200DataItemVisibility[keyof typeof MyVideos200DataItemVisibility];


export const MyVideos200DataItemVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
