/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { MyVideos200DataItem } from './myVideos200DataItem';
import type { MyVideos200Meta } from './myVideos200Meta';

export type MyVideos200 = {
  success: boolean;
  data: MyVideos200DataItem[];
  meta?: MyVideos200Meta;
  message?: string;
};
