/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ReactBodyTwoType = typeof ReactBodyTwoType[keyof typeof ReactBodyTwoType];


export const ReactBodyTwoType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
