/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { React200Data } from './react200Data';

export type React200 = {
  success: boolean;
  data: React200Data;
  message?: string;
};
