/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ReactBodyThreeType } from './reactBodyThreeType';

export type ReactBodyThree = {
  type: ReactBodyThreeType;
};
