/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ReactBodyOneType } from './reactBodyOneType';

export type ReactBodyOne = {
  type: ReactBodyOneType;
};
