/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RecordView200Data } from './recordView200Data';

export type RecordView200 = {
  success: boolean;
  data: RecordView200Data;
  message?: string;
};
