/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveVideo200Data } from './removeVideo200Data';

export type RemoveVideo200 = {
  success: boolean;
  data: RemoveVideo200Data;
  message?: string;
};
