/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveVideoFromPlaylist200Data } from './removeVideoFromPlaylist200Data';

export type RemoveVideoFromPlaylist200 = {
  success: boolean;
  data: RemoveVideoFromPlaylist200Data;
  message?: string;
};
