/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveComment200Data } from './removeComment200Data';

export type RemoveComment200 = {
  success: boolean;
  data: RemoveComment200Data;
  message?: string;
};
