/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemovePlaylist200Data } from './removePlaylist200Data';

export type RemovePlaylist200 = {
  success: boolean;
  data: RemovePlaylist200Data;
  message?: string;
};
