/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveChannel200Data } from './removeChannel200Data';

export type RemoveChannel200 = {
  success: boolean;
  data: RemoveChannel200Data;
  message?: string;
};
