/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ReorderPlaylist200Data } from './reorderPlaylist200Data';

export type ReorderPlaylist200 = {
  success: boolean;
  data: ReorderPlaylist200Data;
  message?: string;
};
