/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { SearchVideos200DataItem } from './searchVideos200DataItem';
import type { SearchVideos200Meta } from './searchVideos200Meta';

export type SearchVideos200 = {
  success: boolean;
  data: SearchVideos200DataItem[];
  meta?: SearchVideos200Meta;
  message?: string;
};
