/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { SearchVideos200DataItemChannel } from './searchVideos200DataItemChannel';

export type SearchVideos200DataItem = {
  id: string;
  title: string;
  description: string | null;
  thumbnailUrl: string | null;
  videoUrl: string;
  views: number;
  channelId: string;
  channel: SearchVideos200DataItemChannel;
  createdAt: string;
  updatedAt: string;
};
