/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { SearchChannels200DataItem } from './searchChannels200DataItem';
import type { SearchChannels200Meta } from './searchChannels200Meta';

export type SearchChannels200 = {
  success: boolean;
  data: SearchChannels200DataItem[];
  meta?: SearchChannels200Meta;
  message?: string;
};
