/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ShowVideo200DataChannel = {
  id: string;
  name: string;
  avatarUrl: string | null;
  subscriberCount: number;
  isSubscribed: boolean;
};
