/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowVideo200DataChannel } from './showVideo200DataChannel';
import type { ShowVideo200DataVisibility } from './showVideo200DataVisibility';

export type ShowVideo200Data = {
  id: string;
  channelId: string;
  title: string;
  description: string | null;
  videoUrl: string;
  thumbnailUrl: string | null;
  visibility: ShowVideo200DataVisibility;
  views: number;
  likes: number;
  dislikes: number;
  myReaction: 'LIKE' | 'DISLIKE' | null;
  channel: ShowVideo200DataChannel;
  createdAt: string;
  updatedAt: string;
};
