/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowPlaylist200Data } from './showPlaylist200Data';

export type ShowPlaylist200 = {
  success: boolean;
  data: ShowPlaylist200Data;
  message?: string;
};
