/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ShowVideo200DataVisibility = typeof ShowVideo200DataVisibility[keyof typeof ShowVideo200DataVisibility];


export const ShowVideo200DataVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
