/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowPlaylist200DataVideosItemVideo } from './showPlaylist200DataVideosItemVideo';

export type ShowPlaylist200DataVideosItem = {
  id: string;
  position: number;
  createdAt: string;
  video: ShowPlaylist200DataVideosItemVideo;
};
