/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowVideoAuthed200Data } from './showVideoAuthed200Data';

export type ShowVideoAuthed200 = {
  success: boolean;
  data: ShowVideoAuthed200Data;
  message?: string;
};
