/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowChannelAuthed200Data } from './showChannelAuthed200Data';

export type ShowChannelAuthed200 = {
  success: boolean;
  data: ShowChannelAuthed200Data;
  message?: string;
};
