/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowChannel200Data } from './showChannel200Data';

export type ShowChannel200 = {
  success: boolean;
  data: ShowChannel200Data;
  message?: string;
};
