/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ShowVideoAuthed200DataVisibility = typeof ShowVideoAuthed200DataVisibility[keyof typeof ShowVideoAuthed200DataVisibility];


export const ShowVideoAuthed200DataVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
