/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowVideoAuthed200DataChannel } from './showVideoAuthed200DataChannel';
import type { ShowVideoAuthed200DataVisibility } from './showVideoAuthed200DataVisibility';

export type ShowVideoAuthed200Data = {
  id: string;
  channelId: string;
  title: string;
  description: string | null;
  videoUrl: string;
  thumbnailUrl: string | null;
  visibility: ShowVideoAuthed200DataVisibility;
  views: number;
  likes: number;
  dislikes: number;
  myReaction: 'LIKE' | 'DISLIKE' | null;
  channel: ShowVideoAuthed200DataChannel;
  createdAt: string;
  updatedAt: string;
};
