/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type ShowPlaylist200DataVisibility = typeof ShowPlaylist200DataVisibility[keyof typeof ShowPlaylist200DataVisibility];


export const ShowPlaylist200DataVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
} as const;
