/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowVideo200Data } from './showVideo200Data';

export type ShowVideo200 = {
  success: boolean;
  data: ShowVideo200Data;
  message?: string;
};
