/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowPlaylist200DataVideosItem } from './showPlaylist200DataVideosItem';
import type { ShowPlaylist200DataVisibility } from './showPlaylist200DataVisibility';

export type ShowPlaylist200Data = {
  id: string;
  name: string;
  description: string | null;
  visibility: ShowPlaylist200DataVisibility;
  userId: string;
  videos: ShowPlaylist200DataVideosItem[];
  createdAt: string;
  updatedAt: string;
};
