/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ToggleSubscription200Data } from './toggleSubscription200Data';

export type ToggleSubscription200 = {
  success: boolean;
  data: ToggleSubscription200Data;
  message?: string;
};
