/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export interface User {
  id?: string;
  name: string;
  email: string;
  readonly emailVerified?: boolean;
  image?: string;
  createdAt: string;
  updatedAt: string;
}
