/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AddVideoToPlaylist200,
  AddVideoToPlaylistBodyOne,
  AddVideoToPlaylistBodyThree,
  AddVideoToPlaylistBodyTwo,
  CreatePlaylist200,
  CreatePlaylistBodyOne,
  CreatePlaylistBodyThree,
  CreatePlaylistBodyTwo,
  EditPlaylist200,
  EditPlaylistBodyOne,
  EditPlaylistBodyThree,
  EditPlaylistBodyTwo,
  ListMyPlaylists200,
  ListMyPlaylistsParams,
  RemovePlaylist200,
  RemoveVideoFromPlaylist200,
  ReorderPlaylist200,
  ReorderPlaylistBodyOne,
  ReorderPlaylistBodyThree,
  ReorderPlaylistBodyTwo,
  ShowPlaylist200
} from '../model';





/**
 * get a public playlist by id
 * @summary show
 */
export type showPlaylistResponse200 = {
  data: ShowPlaylist200
  status: 200
}

export type showPlaylistResponseSuccess = (showPlaylistResponse200) & {
  headers: Headers;
};
;

export type showPlaylistResponse = (showPlaylistResponseSuccess)

export const getShowPlaylistUrl = (id: string,) => {




  return `http://localhost:3000/api/playlists/show/${id}`
}

export const showPlaylist = async (id: string, options?: RequestInit): Promise<showPlaylistResponse> => {

  const res = await fetch(getShowPlaylistUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showPlaylistResponse
}





export const getShowPlaylistQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/api/playlists/show/${id}`
    ] as const;
    }


export const getShowPlaylistQueryOptions = <TData = Awaited<ReturnType<typeof showPlaylist>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showPlaylist>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowPlaylistQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPlaylist>>> = ({ signal }) => showPlaylist(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showPlaylist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowPlaylistQueryResult = NonNullable<Awaited<ReturnType<typeof showPlaylist>>>
export type ShowPlaylistQueryError = unknown


/**
 * @summary show
 */

export function createShowPlaylist<TData = Awaited<ReturnType<typeof showPlaylist>>, TError = unknown>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showPlaylist>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getShowPlaylistQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * list the authenticated user's playlists
 * @summary myList
 */
export type listMyPlaylistsResponse200 = {
  data: ListMyPlaylists200
  status: 200
}

export type listMyPlaylistsResponseSuccess = (listMyPlaylistsResponse200) & {
  headers: Headers;
};
;

export type listMyPlaylistsResponse = (listMyPlaylistsResponseSuccess)

export const getListMyPlaylistsUrl = (params: ListMyPlaylistsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/playlists/me?${stringifiedParams}` : `http://localhost:3000/api/playlists/me`
}

export const listMyPlaylists = async (params: ListMyPlaylistsParams, options?: RequestInit): Promise<listMyPlaylistsResponse> => {

  const res = await fetch(getListMyPlaylistsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMyPlaylistsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listMyPlaylistsResponse
}





export const getListMyPlaylistsQueryKey = (params?: ListMyPlaylistsParams,) => {
    return [
    `http://localhost:3000/api/playlists/me`, ...(params ? [params] : [])
    ] as const;
    }


export const getListMyPlaylistsQueryOptions = <TData = Awaited<ReturnType<typeof listMyPlaylists>>, TError = unknown>(params: ListMyPlaylistsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listMyPlaylists>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyPlaylistsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyPlaylists>>> = ({ signal }) => listMyPlaylists(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listMyPlaylists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyPlaylists>>>
export type ListMyPlaylistsQueryError = unknown


/**
 * @summary myList
 */

export function createListMyPlaylists<TData = Awaited<ReturnType<typeof listMyPlaylists>>, TError = unknown>(
 params: () =>  ListMyPlaylistsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listMyPlaylists>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListMyPlaylistsQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * create a new playlist
 * @summary create
 */
export type createPlaylistResponse200 = {
  data: CreatePlaylist200
  status: 200
}

export type createPlaylistResponseSuccess = (createPlaylistResponse200) & {
  headers: Headers;
};
;

export type createPlaylistResponse = (createPlaylistResponseSuccess)

export const getCreatePlaylistUrl = () => {




  return `http://localhost:3000/api/playlists/me`
}

export const createPlaylist = async (createPlaylistBody: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree, options?: RequestInit): Promise<createPlaylistResponse> => {

  const res = await fetch(getCreatePlaylistUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      createPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPlaylistResponse
}




export const getCreatePlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createPlaylist>>, TError,{data: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createPlaylist>>, TError,{data: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree}, TContext> => {

const mutationKey = ['createPlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlaylist>>, {data: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  createPlaylist(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof createPlaylist>>>
    export type CreatePlaylistMutationBody = CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree
    export type CreatePlaylistMutationError = unknown

    /**
 * @summary create
 */
export const createCreatePlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createPlaylist>>, TError,{data: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createPlaylist>>,
        TError,
        {data: CreatePlaylistBodyOne | CreatePlaylistBodyTwo | CreatePlaylistBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getCreatePlaylistMutationOptions(options?.()) }), queryClient);
    }
    /**
 * update a playlist owned by the authenticated user
 * @summary edit
 */
export type editPlaylistResponse200 = {
  data: EditPlaylist200
  status: 200
}

export type editPlaylistResponseSuccess = (editPlaylistResponse200) & {
  headers: Headers;
};
;

export type editPlaylistResponse = (editPlaylistResponseSuccess)

export const getEditPlaylistUrl = (id: string,) => {




  return `http://localhost:3000/api/playlists/me/${id}`
}

export const editPlaylist = async (id: string,
    editPlaylistBody: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree, options?: RequestInit): Promise<editPlaylistResponse> => {

  const res = await fetch(getEditPlaylistUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(
      editPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editPlaylistResponse
}




export const getEditPlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editPlaylist>>, TError,{id: string;data: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof editPlaylist>>, TError,{id: string;data: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree}, TContext> => {

const mutationKey = ['editPlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editPlaylist>>, {id: string;data: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  editPlaylist(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof editPlaylist>>>
    export type EditPlaylistMutationBody = EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree
    export type EditPlaylistMutationError = unknown

    /**
 * @summary edit
 */
export const createEditPlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editPlaylist>>, TError,{id: string;data: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof editPlaylist>>,
        TError,
        {id: string;data: EditPlaylistBodyOne | EditPlaylistBodyTwo | EditPlaylistBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getEditPlaylistMutationOptions(options?.()) }), queryClient);
    }
    /**
 * delete a playlist owned by the authenticated user
 * @summary remove
 */
export type removePlaylistResponse200 = {
  data: RemovePlaylist200
  status: 200
}

export type removePlaylistResponseSuccess = (removePlaylistResponse200) & {
  headers: Headers;
};
;

export type removePlaylistResponse = (removePlaylistResponseSuccess)

export const getRemovePlaylistUrl = (id: string,) => {




  return `http://localhost:3000/api/playlists/me/${id}`
}

export const removePlaylist = async (id: string, options?: RequestInit): Promise<removePlaylistResponse> => {

  const res = await fetch(getRemovePlaylistUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removePlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removePlaylistResponse
}




export const getRemovePlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removePlaylist>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof removePlaylist>>, TError,{id: string}, TContext> => {

const mutationKey = ['removePlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removePlaylist>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  removePlaylist(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemovePlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof removePlaylist>>>

    export type RemovePlaylistMutationError = unknown

    /**
 * @summary remove
 */
export const createRemovePlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removePlaylist>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removePlaylist>>,
        TError,
        {id: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRemovePlaylistMutationOptions(options?.()) }), queryClient);
    }
    /**
 * add a video to a playlist
 * @summary addVideo
 */
export type addVideoToPlaylistResponse200 = {
  data: AddVideoToPlaylist200
  status: 200
}

export type addVideoToPlaylistResponseSuccess = (addVideoToPlaylistResponse200) & {
  headers: Headers;
};
;

export type addVideoToPlaylistResponse = (addVideoToPlaylistResponseSuccess)

export const getAddVideoToPlaylistUrl = (id: string,) => {




  return `http://localhost:3000/api/playlists/me/${id}/videos`
}

export const addVideoToPlaylist = async (id: string,
    addVideoToPlaylistBody: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree, options?: RequestInit): Promise<addVideoToPlaylistResponse> => {

  const res = await fetch(getAddVideoToPlaylistUrl(id),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      addVideoToPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addVideoToPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addVideoToPlaylistResponse
}




export const getAddVideoToPlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addVideoToPlaylist>>, TError,{id: string;data: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof addVideoToPlaylist>>, TError,{id: string;data: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree}, TContext> => {

const mutationKey = ['addVideoToPlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addVideoToPlaylist>>, {id: string;data: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  addVideoToPlaylist(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddVideoToPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof addVideoToPlaylist>>>
    export type AddVideoToPlaylistMutationBody = AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree
    export type AddVideoToPlaylistMutationError = unknown

    /**
 * @summary addVideo
 */
export const createAddVideoToPlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addVideoToPlaylist>>, TError,{id: string;data: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof addVideoToPlaylist>>,
        TError,
        {id: string;data: AddVideoToPlaylistBodyOne | AddVideoToPlaylistBodyTwo | AddVideoToPlaylistBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getAddVideoToPlaylistMutationOptions(options?.()) }), queryClient);
    }
    /**
 * remove a video from a playlist
 * @summary removeVideo
 */
export type removeVideoFromPlaylistResponse200 = {
  data: RemoveVideoFromPlaylist200
  status: 200
}

export type removeVideoFromPlaylistResponseSuccess = (removeVideoFromPlaylistResponse200) & {
  headers: Headers;
};
;

export type removeVideoFromPlaylistResponse = (removeVideoFromPlaylistResponseSuccess)

export const getRemoveVideoFromPlaylistUrl = (id: string,
    videoId: string,) => {




  return `http://localhost:3000/api/playlists/me/${id}/videos/${videoId}`
}

export const removeVideoFromPlaylist = async (id: string,
    videoId: string, options?: RequestInit): Promise<removeVideoFromPlaylistResponse> => {

  const res = await fetch(getRemoveVideoFromPlaylistUrl(id,videoId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeVideoFromPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeVideoFromPlaylistResponse
}




export const getRemoveVideoFromPlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeVideoFromPlaylist>>, TError,{id: string;videoId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof removeVideoFromPlaylist>>, TError,{id: string;videoId: string}, TContext> => {

const mutationKey = ['removeVideoFromPlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeVideoFromPlaylist>>, {id: string;videoId: string}> = (props) => {
          const {id,videoId} = props ?? {};

          return  removeVideoFromPlaylist(id,videoId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveVideoFromPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof removeVideoFromPlaylist>>>

    export type RemoveVideoFromPlaylistMutationError = unknown

    /**
 * @summary removeVideo
 */
export const createRemoveVideoFromPlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeVideoFromPlaylist>>, TError,{id: string;videoId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removeVideoFromPlaylist>>,
        TError,
        {id: string;videoId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRemoveVideoFromPlaylistMutationOptions(options?.()) }), queryClient);
    }
    /**
 * reorder videos in a playlist by providing full ordered videoIds array
 * @summary reorder
 */
export type reorderPlaylistResponse200 = {
  data: ReorderPlaylist200
  status: 200
}

export type reorderPlaylistResponseSuccess = (reorderPlaylistResponse200) & {
  headers: Headers;
};
;

export type reorderPlaylistResponse = (reorderPlaylistResponseSuccess)

export const getReorderPlaylistUrl = (id: string,) => {




  return `http://localhost:3000/api/playlists/me/${id}/reorder`
}

export const reorderPlaylist = async (id: string,
    reorderPlaylistBody: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree, options?: RequestInit): Promise<reorderPlaylistResponse> => {

  const res = await fetch(getReorderPlaylistUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(
      reorderPlaylistBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: reorderPlaylistResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as reorderPlaylistResponse
}




export const getReorderPlaylistMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof reorderPlaylist>>, TError,{id: string;data: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof reorderPlaylist>>, TError,{id: string;data: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree}, TContext> => {

const mutationKey = ['reorderPlaylist'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderPlaylist>>, {id: string;data: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  reorderPlaylist(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof reorderPlaylist>>>
    export type ReorderPlaylistMutationBody = ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree
    export type ReorderPlaylistMutationError = unknown

    /**
 * @summary reorder
 */
export const createReorderPlaylist = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof reorderPlaylist>>, TError,{id: string;data: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof reorderPlaylist>>,
        TError,
        {id: string;data: ReorderPlaylistBodyOne | ReorderPlaylistBodyTwo | ReorderPlaylistBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getReorderPlaylistMutationOptions(options?.()) }), queryClient);
    }
