/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  MyFeed200,
  MyFeedParams,
  MySubscriptions200,
  MySubscriptionsParams,
  ToggleSubscription200
} from '../model';





/**
 * subscribe or unsubscribe from a channel — toggles off if already subscribed
 * @summary toggle
 */
export type toggleSubscriptionResponse200 = {
  data: ToggleSubscription200
  status: 200
}

export type toggleSubscriptionResponseSuccess = (toggleSubscriptionResponse200) & {
  headers: Headers;
};
;

export type toggleSubscriptionResponse = (toggleSubscriptionResponseSuccess)

export const getToggleSubscriptionUrl = (channelId: string,) => {




  return `http://localhost:3000/api/subscriptions/${channelId}`
}

export const toggleSubscription = async (channelId: string, options?: RequestInit): Promise<toggleSubscriptionResponse> => {

  const res = await fetch(getToggleSubscriptionUrl(channelId),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: toggleSubscriptionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as toggleSubscriptionResponse
}




export const getToggleSubscriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleSubscription>>, TError,{channelId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof toggleSubscription>>, TError,{channelId: string}, TContext> => {

const mutationKey = ['toggleSubscription'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleSubscription>>, {channelId: string}> = (props) => {
          const {channelId} = props ?? {};

          return  toggleSubscription(channelId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToggleSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof toggleSubscription>>>

    export type ToggleSubscriptionMutationError = unknown

    /**
 * @summary toggle
 */
export const createToggleSubscription = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof toggleSubscription>>, TError,{channelId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof toggleSubscription>>,
        TError,
        {channelId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getToggleSubscriptionMutationOptions(options?.()) }), queryClient);
    }
    /**
 * list channels the authenticated user is subscribed to
 * @summary myList
 */
export type mySubscriptionsResponse200 = {
  data: MySubscriptions200
  status: 200
}

export type mySubscriptionsResponseSuccess = (mySubscriptionsResponse200) & {
  headers: Headers;
};
;

export type mySubscriptionsResponse = (mySubscriptionsResponseSuccess)

export const getMySubscriptionsUrl = (params: MySubscriptionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/subscriptions/me?${stringifiedParams}` : `http://localhost:3000/api/subscriptions/me`
}

export const mySubscriptions = async (params: MySubscriptionsParams, options?: RequestInit): Promise<mySubscriptionsResponse> => {

  const res = await fetch(getMySubscriptionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: mySubscriptionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as mySubscriptionsResponse
}





export const getMySubscriptionsQueryKey = (params?: MySubscriptionsParams,) => {
    return [
    `http://localhost:3000/api/subscriptions/me`, ...(params ? [params] : [])
    ] as const;
    }


export const getMySubscriptionsQueryOptions = <TData = Awaited<ReturnType<typeof mySubscriptions>>, TError = unknown>(params: MySubscriptionsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof mySubscriptions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMySubscriptionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mySubscriptions>>> = ({ signal }) => mySubscriptions(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof mySubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MySubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof mySubscriptions>>>
export type MySubscriptionsQueryError = unknown


/**
 * @summary myList
 */

export function createMySubscriptions<TData = Awaited<ReturnType<typeof mySubscriptions>>, TError = unknown>(
 params: () =>  MySubscriptionsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof mySubscriptions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getMySubscriptionsQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * list videos from subscribed channels
 * @summary myFeed
 */
export type myFeedResponse200 = {
  data: MyFeed200
  status: 200
}

export type myFeedResponseSuccess = (myFeedResponse200) & {
  headers: Headers;
};
;

export type myFeedResponse = (myFeedResponseSuccess)

export const getMyFeedUrl = (params: MyFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/subscriptions/me/feed?${stringifiedParams}` : `http://localhost:3000/api/subscriptions/me/feed`
}

export const myFeed = async (params: MyFeedParams, options?: RequestInit): Promise<myFeedResponse> => {

  const res = await fetch(getMyFeedUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: myFeedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as myFeedResponse
}





export const getMyFeedQueryKey = (params?: MyFeedParams,) => {
    return [
    `http://localhost:3000/api/subscriptions/me/feed`, ...(params ? [params] : [])
    ] as const;
    }


export const getMyFeedQueryOptions = <TData = Awaited<ReturnType<typeof myFeed>>, TError = unknown>(params: MyFeedParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myFeed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMyFeedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof myFeed>>> = ({ signal }) => myFeed(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof myFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MyFeedQueryResult = NonNullable<Awaited<ReturnType<typeof myFeed>>>
export type MyFeedQueryError = unknown


/**
 * @summary myFeed
 */

export function createMyFeed<TData = Awaited<ReturnType<typeof myFeed>>, TError = unknown>(
 params: () =>  MyFeedParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myFeed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getMyFeedQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




