/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  SearchChannels200,
  SearchChannelsParams,
  SearchVideos200,
  SearchVideosParams
} from '../model';





/**
 * search videos by title or description
 * @summary searchVideos
 */
export type searchVideosResponse200 = {
  data: SearchVideos200
  status: 200
}

export type searchVideosResponseSuccess = (searchVideosResponse200) & {
  headers: Headers;
};
;

export type searchVideosResponse = (searchVideosResponseSuccess)

export const getSearchVideosUrl = (params: SearchVideosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/search/videos?${stringifiedParams}` : `http://localhost:3000/api/search/videos`
}

export const searchVideos = async (params: SearchVideosParams, options?: RequestInit): Promise<searchVideosResponse> => {

  const res = await fetch(getSearchVideosUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchVideosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchVideosResponse
}





export const getSearchVideosQueryKey = (params?: SearchVideosParams,) => {
    return [
    `http://localhost:3000/api/search/videos`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchVideosQueryOptions = <TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(params: SearchVideosParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchVideosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVideos>>> = ({ signal }) => searchVideos(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchVideosQueryResult = NonNullable<Awaited<ReturnType<typeof searchVideos>>>
export type SearchVideosQueryError = unknown


/**
 * @summary searchVideos
 */

export function createSearchVideos<TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(
 params: () =>  SearchVideosParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getSearchVideosQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * search channels by name or description
 * @summary searchChannels
 */
export type searchChannelsResponse200 = {
  data: SearchChannels200
  status: 200
}

export type searchChannelsResponseSuccess = (searchChannelsResponse200) & {
  headers: Headers;
};
;

export type searchChannelsResponse = (searchChannelsResponseSuccess)

export const getSearchChannelsUrl = (params: SearchChannelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/search/channels?${stringifiedParams}` : `http://localhost:3000/api/search/channels`
}

export const searchChannels = async (params: SearchChannelsParams, options?: RequestInit): Promise<searchChannelsResponse> => {

  const res = await fetch(getSearchChannelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchChannelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchChannelsResponse
}





export const getSearchChannelsQueryKey = (params?: SearchChannelsParams,) => {
    return [
    `http://localhost:3000/api/search/channels`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchChannelsQueryOptions = <TData = Awaited<ReturnType<typeof searchChannels>>, TError = unknown>(params: SearchChannelsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchChannelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchChannels>>> = ({ signal }) => searchChannels(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof searchChannels>>>
export type SearchChannelsQueryError = unknown


/**
 * @summary searchChannels
 */

export function createSearchChannels<TData = Awaited<ReturnType<typeof searchChannels>>, TError = unknown>(
 params: () =>  SearchChannelsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof searchChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getSearchChannelsQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




