/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateChannel200,
  CreateChannelBodyOne,
  CreateChannelBodyThree,
  CreateChannelBodyTwo,
  EditChannel200,
  EditChannelBodyOne,
  EditChannelBodyThree,
  EditChannelBodyTwo,
  ListChannels200,
  ListChannelsParams,
  MyChannel200,
  RemoveChannel200,
  ShowChannel200,
  ShowChannelAuthed200
} from '../model';





/**
 * list all channels
 * @summary list
 */
export type listChannelsResponse200 = {
  data: ListChannels200
  status: 200
}

export type listChannelsResponseSuccess = (listChannelsResponse200) & {
  headers: Headers;
};
;

export type listChannelsResponse = (listChannelsResponseSuccess)

export const getListChannelsUrl = (params: ListChannelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/channels/?${stringifiedParams}` : `http://localhost:3000/api/channels/`
}

export const listChannels = async (params: ListChannelsParams, options?: RequestInit): Promise<listChannelsResponse> => {

  const res = await fetch(getListChannelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listChannelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listChannelsResponse
}





export const getListChannelsQueryKey = (params?: ListChannelsParams,) => {
    return [
    `http://localhost:3000/api/channels/`, ...(params ? [params] : [])
    ] as const;
    }


export const getListChannelsQueryOptions = <TData = Awaited<ReturnType<typeof listChannels>>, TError = unknown>(params: ListChannelsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChannelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannels>>> = ({ signal }) => listChannels(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof listChannels>>>
export type ListChannelsQueryError = unknown


/**
 * @summary list
 */

export function createListChannels<TData = Awaited<ReturnType<typeof listChannels>>, TError = unknown>(
 params: () =>  ListChannelsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listChannels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getListChannelsQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * get a channel by id
 * @summary show
 */
export type showChannelResponse200 = {
  data: ShowChannel200
  status: 200
}

export type showChannelResponseSuccess = (showChannelResponse200) & {
  headers: Headers;
};
;

export type showChannelResponse = (showChannelResponseSuccess)

export const getShowChannelUrl = (id: string,) => {




  return `http://localhost:3000/api/channels/show/${id}`
}

export const showChannel = async (id: string, options?: RequestInit): Promise<showChannelResponse> => {

  const res = await fetch(getShowChannelUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showChannelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showChannelResponse
}





export const getShowChannelQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/api/channels/show/${id}`
    ] as const;
    }


export const getShowChannelQueryOptions = <TData = Awaited<ReturnType<typeof showChannel>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showChannel>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowChannelQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showChannel>>> = ({ signal }) => showChannel(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showChannel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowChannelQueryResult = NonNullable<Awaited<ReturnType<typeof showChannel>>>
export type ShowChannelQueryError = unknown


/**
 * @summary show
 */

export function createShowChannel<TData = Awaited<ReturnType<typeof showChannel>>, TError = unknown>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showChannel>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getShowChannelQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * get a channel by id with subscription status
 * @summary showAuthed
 */
export type showChannelAuthedResponse200 = {
  data: ShowChannelAuthed200
  status: 200
}

export type showChannelAuthedResponseSuccess = (showChannelAuthedResponse200) & {
  headers: Headers;
};
;

export type showChannelAuthedResponse = (showChannelAuthedResponseSuccess)

export const getShowChannelAuthedUrl = (id: string,) => {




  return `http://localhost:3000/api/channels/show/${id}/authed`
}

export const showChannelAuthed = async (id: string, options?: RequestInit): Promise<showChannelAuthedResponse> => {

  const res = await fetch(getShowChannelAuthedUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showChannelAuthedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as showChannelAuthedResponse
}





export const getShowChannelAuthedQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/api/channels/show/${id}/authed`
    ] as const;
    }


export const getShowChannelAuthedQueryOptions = <TData = Awaited<ReturnType<typeof showChannelAuthed>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showChannelAuthed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowChannelAuthedQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof showChannelAuthed>>> = ({ signal }) => showChannelAuthed(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showChannelAuthed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowChannelAuthedQueryResult = NonNullable<Awaited<ReturnType<typeof showChannelAuthed>>>
export type ShowChannelAuthedQueryError = unknown


/**
 * @summary showAuthed
 */

export function createShowChannelAuthed<TData = Awaited<ReturnType<typeof showChannelAuthed>>, TError = unknown>(
 id: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showChannelAuthed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getShowChannelAuthedQueryOptions(id(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * get the authenticated user's channel
 * @summary me
 */
export type myChannelResponse200 = {
  data: MyChannel200
  status: 200
}

export type myChannelResponseSuccess = (myChannelResponse200) & {
  headers: Headers;
};
;

export type myChannelResponse = (myChannelResponseSuccess)

export const getMyChannelUrl = () => {




  return `http://localhost:3000/api/channels/me`
}

export const myChannel = async ( options?: RequestInit): Promise<myChannelResponse> => {

  const res = await fetch(getMyChannelUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: myChannelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as myChannelResponse
}





export const getMyChannelQueryKey = () => {
    return [
    `http://localhost:3000/api/channels/me`
    ] as const;
    }


export const getMyChannelQueryOptions = <TData = Awaited<ReturnType<typeof myChannel>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myChannel>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMyChannelQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof myChannel>>> = ({ signal }) => myChannel({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof myChannel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MyChannelQueryResult = NonNullable<Awaited<ReturnType<typeof myChannel>>>
export type MyChannelQueryError = unknown


/**
 * @summary me
 */

export function createMyChannel<TData = Awaited<ReturnType<typeof myChannel>>, TError = unknown>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myChannel>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getMyChannelQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




/**
 * create a channel for the authenticated user
 * @summary create
 */
export type createChannelResponse200 = {
  data: CreateChannel200
  status: 200
}

export type createChannelResponseSuccess = (createChannelResponse200) & {
  headers: Headers;
};
;

export type createChannelResponse = (createChannelResponseSuccess)

export const getCreateChannelUrl = () => {




  return `http://localhost:3000/api/channels/me`
}

export const createChannel = async (createChannelBody: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree, options?: RequestInit): Promise<createChannelResponse> => {

  const res = await fetch(getCreateChannelUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      createChannelBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createChannelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createChannelResponse
}




export const getCreateChannelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{data: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{data: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree}, TContext> => {

const mutationKey = ['createChannel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChannel>>, {data: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  createChannel(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateChannelMutationResult = NonNullable<Awaited<ReturnType<typeof createChannel>>>
    export type CreateChannelMutationBody = CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree
    export type CreateChannelMutationError = unknown

    /**
 * @summary create
 */
export const createCreateChannel = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createChannel>>, TError,{data: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createChannel>>,
        TError,
        {data: CreateChannelBodyOne | CreateChannelBodyTwo | CreateChannelBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateChannelMutationOptions(options?.()) }), queryClient);
    }
    /**
 * update the authenticated user's channel
 * @summary edit
 */
export type editChannelResponse200 = {
  data: EditChannel200
  status: 200
}

export type editChannelResponseSuccess = (editChannelResponse200) & {
  headers: Headers;
};
;

export type editChannelResponse = (editChannelResponseSuccess)

export const getEditChannelUrl = () => {




  return `http://localhost:3000/api/channels/me`
}

export const editChannel = async (editChannelBody: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree, options?: RequestInit): Promise<editChannelResponse> => {

  const res = await fetch(getEditChannelUrl(),
  {
    ...options,
    method: 'PUT'
    ,
    body: JSON.stringify(
      editChannelBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: editChannelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as editChannelResponse
}




export const getEditChannelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editChannel>>, TError,{data: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof editChannel>>, TError,{data: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree}, TContext> => {

const mutationKey = ['editChannel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editChannel>>, {data: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  editChannel(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditChannelMutationResult = NonNullable<Awaited<ReturnType<typeof editChannel>>>
    export type EditChannelMutationBody = EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree
    export type EditChannelMutationError = unknown

    /**
 * @summary edit
 */
export const createEditChannel = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof editChannel>>, TError,{data: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof editChannel>>,
        TError,
        {data: EditChannelBodyOne | EditChannelBodyTwo | EditChannelBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getEditChannelMutationOptions(options?.()) }), queryClient);
    }
    /**
 * delete the authenticated user's channel
 * @summary remove
 */
export type removeChannelResponse200 = {
  data: RemoveChannel200
  status: 200
}

export type removeChannelResponseSuccess = (removeChannelResponse200) & {
  headers: Headers;
};
;

export type removeChannelResponse = (removeChannelResponseSuccess)

export const getRemoveChannelUrl = () => {




  return `http://localhost:3000/api/channels/me`
}

export const removeChannel = async ( options?: RequestInit): Promise<removeChannelResponse> => {

  const res = await fetch(getRemoveChannelUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeChannelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeChannelResponse
}




export const getRemoveChannelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeChannel>>, TError,void, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof removeChannel>>, TError,void, TContext> => {

const mutationKey = ['removeChannel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeChannel>>, void> = () => {


          return  removeChannel(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveChannelMutationResult = NonNullable<Awaited<ReturnType<typeof removeChannel>>>

    export type RemoveChannelMutationError = unknown

    /**
 * @summary remove
 */
export const createRemoveChannel = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removeChannel>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removeChannel>>,
        TError,
        void,
        TContext
      > => {
      return createMutation(() => ({ ...getRemoveChannelMutationOptions(options?.()) }), queryClient);
    }
