/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  MyReactions200,
  MyReactionsParams,
  React200,
  ReactBodyOne,
  ReactBodyThree,
  ReactBodyTwo
} from '../model';





/**
 * like or dislike a video — toggles off if same type sent again
 * @summary react
 */
export type reactResponse200 = {
  data: React200
  status: 200
}

export type reactResponseSuccess = (reactResponse200) & {
  headers: Headers;
};
;

export type reactResponse = (reactResponseSuccess)

export const getReactUrl = (videoId: string,) => {




  return `http://localhost:3000/api/reactions/${videoId}`
}

export const react = async (videoId: string,
    reactBody: ReactBodyOne | ReactBodyTwo | ReactBodyThree, options?: RequestInit): Promise<reactResponse> => {

  const res = await fetch(getReactUrl(videoId),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      reactBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: reactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as reactResponse
}




export const getReactMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof react>>, TError,{videoId: string;data: ReactBodyOne | ReactBodyTwo | ReactBodyThree}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof react>>, TError,{videoId: string;data: ReactBodyOne | ReactBodyTwo | ReactBodyThree}, TContext> => {

const mutationKey = ['react'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof react>>, {videoId: string;data: ReactBodyOne | ReactBodyTwo | ReactBodyThree}> = (props) => {
          const {videoId,data} = props ?? {};

          return  react(videoId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReactMutationResult = NonNullable<Awaited<ReturnType<typeof react>>>
    export type ReactMutationBody = ReactBodyOne | ReactBodyTwo | ReactBodyThree
    export type ReactMutationError = unknown

    /**
 * @summary react
 */
export const createReact = <TError = unknown,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof react>>, TError,{videoId: string;data: ReactBodyOne | ReactBodyTwo | ReactBodyThree}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof react>>,
        TError,
        {videoId: string;data: ReactBodyOne | ReactBodyTwo | ReactBodyThree},
        TContext
      > => {
      return createMutation(() => ({ ...getReactMutationOptions(options?.()) }), queryClient);
    }
    /**
 * get the authenticated user's liked/disliked videos
 * @summary myReactions
 */
export type myReactionsResponse200 = {
  data: MyReactions200
  status: 200
}

export type myReactionsResponseSuccess = (myReactionsResponse200) & {
  headers: Headers;
};
;

export type myReactionsResponse = (myReactionsResponseSuccess)

export const getMyReactionsUrl = (params: MyReactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/reactions/me?${stringifiedParams}` : `http://localhost:3000/api/reactions/me`
}

export const myReactions = async (params: MyReactionsParams, options?: RequestInit): Promise<myReactionsResponse> => {

  const res = await fetch(getMyReactionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: myReactionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as myReactionsResponse
}





export const getMyReactionsQueryKey = (params?: MyReactionsParams,) => {
    return [
    `http://localhost:3000/api/reactions/me`, ...(params ? [params] : [])
    ] as const;
    }


export const getMyReactionsQueryOptions = <TData = Awaited<ReturnType<typeof myReactions>>, TError = unknown>(params: MyReactionsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myReactions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMyReactionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof myReactions>>> = ({ signal }) => myReactions(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof myReactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MyReactionsQueryResult = NonNullable<Awaited<ReturnType<typeof myReactions>>>
export type MyReactionsQueryError = unknown


/**
 * @summary myReactions
 */

export function createMyReactions<TData = Awaited<ReturnType<typeof myReactions>>, TError = unknown>(
 params: () =>  MyReactionsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof myReactions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {



  const query = createQuery(() => getMyReactionsQueryOptions(params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




